org = imread('F:\\Code\\LAB property\\data\\RGB\\20170228111043_scene.jpg');
%org = imread('F:\\Code\\LAB property\\data\\RGB\\HoloLens2.jpg');
%org = imread('F:\\Code\\LAB property\\data\\RGB\\p14_1.jpg');
translate = makecform('srgb2lab'); 
lab = applycform(org, translate);
L = lab(:,:,1);
a = lab(:,:,2);
b = lab(:,:,3);
figure(1);
subplot(2,2,1);
imshow(a);
title('(a)a分量图像','FontSize',14,'FontName','隶书','color','b');
subplot(2,2,2);
imshow(b);
title('(b)b分量图像','FontSize',14,'FontName','隶书','color','b');
subplot(2,2,3);
imhist(a);
title('(c)a分量直方图','FontSize',14,'FontName','隶书','color','b');
subplot(2,2,4);
imhist(b);
title('(d)b分量直方图','FontSize',14,'FontName','隶书','color','b');